name: Uncanny Camera
description: A possessed camera. Not the photos you deserve, but the photos you need.

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.3.0
  cupertino_icons: ^0.1.2
  image: ^1.1.31
  image_picker: ^0.4.1
  google_sign_in: ^3.0.3
  firebase_analytics: ^0.3.3
  firebase_auth: ^0.5.9
  firebase_database: ^0.4.6
  firebase_storage: ^0.3.4
  path_provider: ^0.4.0
  intl: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.3.2

flutter:
  uses-material-design: true

flutter_icons:
  image_path: icons/icon.png
  android: true
  ios: true
